/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Model.CourseDetails;
import Model.CourseDetailsDirectory;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.Iterator;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rohan
 */
public class ProfessorCourseCreationJPanel extends javax.swing.JPanel {
 
    

    /**
     * Creates new form ProfessorCourseCreationJPanel
     */
    private JPanel container;
    private CourseDetails coursedetails;
    private CourseDetailsDirectory courseDetailsDirectory;
//    private javax.swing.AbstractAction.JTable tblCourseCatalogue;
//    private CourseDetailsDirectory coursedirectory;
//    private javax.swing.JTable tableCourseCatalog;
    
    //private CourseDetailsDirectory coursedetailsdirectory;
    
    public ProfessorCourseCreationJPanel(JPanel container, CourseDetailsDirectory courseDetailsDirectory,CourseDetails coursedetails) {
        initComponents();
        this.container = container;
        this.courseDetailsDirectory = courseDetailsDirectory;
//        System.out.println(this.courseDetailsDirectory.getCourseList());
        this.coursedetails = coursedetails;
//        tableCourseCatalog= new javax.swing.JTable();
        populateTable();
        DefaultTableModel dtm = (DefaultTableModel) tableCourseCatalog.getModel();
//        System.out.println(this.courseDetailsDirectory);
        
        
    }

//    ProfessorCourseCreationJPanel() {
//        populateTable();
//        
//       
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCreateCourseTitle = new javax.swing.JLabel();
        labelCourseCode = new javax.swing.JLabel();
        labelCourseName = new javax.swing.JLabel();
        labelIntake = new javax.swing.JLabel();
        labelScheduleDays = new javax.swing.JLabel();
        labelScheduleTime = new javax.swing.JLabel();
        textCourseCode = new javax.swing.JTextField();
        textCourseName = new javax.swing.JTextField();
        checkboxMonday = new javax.swing.JCheckBox();
        checkboxTuesday = new javax.swing.JCheckBox();
        checkboxWednesday = new javax.swing.JCheckBox();
        checkboxThursday = new javax.swing.JCheckBox();
        checkboxFriday = new javax.swing.JCheckBox();
        checkboxSaturday = new javax.swing.JCheckBox();
        checkboxSunday = new javax.swing.JCheckBox();
        buttonSave = new javax.swing.JButton();
        jComboBoxIntake = new javax.swing.JComboBox<>();
        jComboBoxStartTimeHH = new javax.swing.JComboBox<>();
        jComboBoxStartTimeMM = new javax.swing.JComboBox<>();
        labelTo = new javax.swing.JLabel();
        jComboBoxEndTimeHH = new javax.swing.JComboBox<>();
        jComboBoxEndTimeMM = new javax.swing.JComboBox<>();
        labelCourseDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textCourseDescription = new javax.swing.JTextArea();
        labelMode = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCourseCatalog = new javax.swing.JTable();
        buttonBack = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        labelProfessorName = new javax.swing.JLabel();
        textProfessorName = new javax.swing.JTextField();

        labelCreateCourseTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelCreateCourseTitle.setText("Create Course");

        labelCourseCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCourseCode.setText("Course Code:");

        labelCourseName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCourseName.setText("Course Name:");

        labelIntake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIntake.setText("Intake:");

        labelScheduleDays.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelScheduleDays.setText("Course Schedule (Days):");

        labelScheduleTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelScheduleTime.setText("Course Schedule (Time):");

        checkboxMonday.setText("Monday");

        checkboxTuesday.setText("Tuesday");

        checkboxWednesday.setText("Wednesday");

        checkboxThursday.setText("Thursday");

        checkboxFriday.setText("Friday");

        checkboxSaturday.setText("Saturday");

        checkboxSunday.setText("Sunday");

        buttonSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });

        jComboBoxIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fall 2023", "Spring 2024", "Fall 2024", "Spring 2025" }));

        jComboBoxStartTimeHH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        jComboBoxStartTimeHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStartTimeHHActionPerformed(evt);
            }
        });

        jComboBoxStartTimeMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        jComboBoxStartTimeMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxStartTimeMMActionPerformed(evt);
            }
        });

        labelTo.setText("to");

        jComboBoxEndTimeHH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", " " }));
        jComboBoxEndTimeHH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEndTimeHHActionPerformed(evt);
            }
        });

        jComboBoxEndTimeMM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", " " }));
        jComboBoxEndTimeMM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEndTimeMMActionPerformed(evt);
            }
        });

        labelCourseDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCourseDescription.setText("Course Description:");

        textCourseDescription.setColumns(20);
        textCourseDescription.setRows(5);
        jScrollPane1.setViewportView(textCourseDescription);

        labelMode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMode.setText("Mode:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "In-Person", "Online" }));

        tableCourseCatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Mode", "Couse Code", "Course Name", "Intake", "Scheduled Day", "Scheduled Time", "Professor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableCourseCatalog);

        buttonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBack.setText("<- Back ");
        buttonBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelProfessorName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProfessorName.setText("Name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(buttonBack)
                        .addGap(477, 477, 477)
                        .addComponent(labelCreateCourseTitle)
                        .addGap(270, 270, 270)
                        .addComponent(buttonLogout))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(labelProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(textProfessorName))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(470, 470, 470)
                                            .addComponent(buttonSave))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(labelCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelScheduleTime, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelScheduleDays, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(labelCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(41, 41, 41)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(checkboxMonday)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(checkboxTuesday))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(jComboBoxStartTimeHH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jComboBoxStartTimeMM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(checkboxWednesday)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(checkboxThursday)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(checkboxFriday)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(checkboxSaturday)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(checkboxSunday))
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addComponent(labelTo)
                                                            .addGap(40, 40, 40)
                                                            .addComponent(jComboBoxEndTimeHH, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                            .addComponent(jComboBoxEndTimeMM, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addComponent(jScrollPane1)
                                                .addComponent(textCourseCode)
                                                .addComponent(jComboBoxIntake, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(textCourseName))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labelMode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(294, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCreateCourseTitle)
                            .addComponent(buttonLogout)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(buttonBack)))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScheduleDays, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxMonday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxTuesday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxWednesday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxThursday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxFriday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxSaturday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkboxSunday, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelScheduleTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStartTimeHH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStartTimeMM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEndTimeHH, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEndTimeMM, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonSave)
                .addGap(66, 66, 66)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxStartTimeHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStartTimeHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStartTimeHHActionPerformed

    private void jComboBoxStartTimeMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStartTimeMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStartTimeMMActionPerformed

    private void jComboBoxEndTimeHHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEndTimeHHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEndTimeHHActionPerformed

    private void jComboBoxEndTimeMMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEndTimeMMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEndTimeMMActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        // TODO add your handling code here:
        
       /*add*/ String mode = jComboBox1.getSelectedItem().toString();
               String coursecode = textCourseCode.getText();
               String coursename = textCourseName.getText();
               String intake = jComboBoxIntake.getSelectedItem().toString();
               String coursedescription = textCourseDescription.getText();
               String professorName = textProfessorName.getText();
//               populateTable();
               //coursedetails.setMode(jComboBox1.getSelectedItem().toString());
       /*add*/ //coursedetails.setCourseCode(textCourseCode.getText());
       /*add*/ //coursedetails.setCourseName(textCourseName.getText());
       /*add*/ //coursedetails.setIntake(jComboBoxIntake.getSelectedItem().toString());
       /*add*/ //coursedetails.setCourseDescription(textCourseDescription.getText());
        
        String startTimeHH = jComboBoxStartTimeHH.getSelectedItem().toString();
        String startTimeMM = jComboBoxStartTimeMM.getSelectedItem().toString();
        String endTimeHH = jComboBoxEndTimeHH.getSelectedItem().toString();
        String endTimeMM = jComboBoxEndTimeMM.getSelectedItem().toString(); 
        
        String result = startTimeHH + ":" + startTimeMM + " - " + endTimeHH +":" + endTimeMM;
        
        //coursedetails.setCourseScheduleTime(result);
        String coursescheduletime = result;
        
        
         String coursescheduledate = getCoursescheduledate();

        CourseDetails cd = courseDetailsDirectory.addCourse();
        
        cd.setMode(mode);
        cd.setProfessorName(professorName);
        cd.setCourseCode(coursecode);
        cd.setCourseDescription(coursedescription);
        cd.setCourseName(coursename);
        cd.setIntake(intake);
        cd.setCourseScheduleDate(coursescheduledate);
        cd.setCourseScheduleTime(coursescheduletime);
//        System.out.println();
        
        populateTable();
        JOptionPane.showMessageDialog(null,"Course added Successfully !");
        
        
//        System.out.println(coursedetails);
    }//GEN-LAST:event_buttonSaveActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout=(CardLayout) container.getLayout();
        layout.previous(container); 
    }//GEN-LAST:event_buttonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonSave;
    private javax.swing.JCheckBox checkboxFriday;
    private javax.swing.JCheckBox checkboxMonday;
    private javax.swing.JCheckBox checkboxSaturday;
    private javax.swing.JCheckBox checkboxSunday;
    private javax.swing.JCheckBox checkboxThursday;
    private javax.swing.JCheckBox checkboxTuesday;
    private javax.swing.JCheckBox checkboxWednesday;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxEndTimeHH;
    private javax.swing.JComboBox<String> jComboBoxEndTimeMM;
    private javax.swing.JComboBox<String> jComboBoxIntake;
    private javax.swing.JComboBox<String> jComboBoxStartTimeHH;
    private javax.swing.JComboBox<String> jComboBoxStartTimeMM;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCourseCode;
    private javax.swing.JLabel labelCourseDescription;
    private javax.swing.JLabel labelCourseName;
    private javax.swing.JLabel labelCreateCourseTitle;
    private javax.swing.JLabel labelIntake;
    private javax.swing.JLabel labelMode;
    private javax.swing.JLabel labelProfessorName;
    private javax.swing.JLabel labelScheduleDays;
    private javax.swing.JLabel labelScheduleTime;
    private javax.swing.JLabel labelTo;
    private javax.swing.JTable tableCourseCatalog;
    private javax.swing.JTextField textCourseCode;
    private javax.swing.JTextArea textCourseDescription;
    private javax.swing.JTextField textCourseName;
    private javax.swing.JTextField textProfessorName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        DefaultTableModel dtm = (DefaultTableModel) tableCourseCatalog.getModel();
        dtm.setRowCount(0);
//        System.out.println(courseDetailsDirectory.getCourseList());
        for (CourseDetails cd : courseDetailsDirectory.getCourseList()) {
            Object[] row = new Object[7];
            row[0]=cd.getMode();
            row[1]=cd.getCourseCode();
            row[2]=cd.getCourseName();
            row[3]=cd.getIntake();
            row[4]=cd.getCourseScheduleDate();
            row[5]=cd.getCourseScheduleTime();
            row[6]=cd.getProfessorName();
            dtm.addRow(row);
              
        }
      
    }

    private String getCoursescheduledate() {
        StringBuilder selectedDays = new StringBuilder();
        if (checkboxMonday.isSelected()) {
        selectedDays.append("Monday, ");
    }
    if (checkboxTuesday.isSelected()) {
        selectedDays.append("Tuesday, ");
    }
    if (checkboxWednesday.isSelected()) {
        selectedDays.append("Wednesday, ");
    }
    if (checkboxThursday.isSelected()) {
        selectedDays.append("Thursday, ");
    }
    if (checkboxFriday.isSelected()) {
        selectedDays.append("Friday, ");
    }
    if (checkboxSaturday.isSelected()) {
        selectedDays.append("Saturday, ");
    }
    if (checkboxSunday.isSelected()) {
        selectedDays.append("Sunday, ");
    }
    
    if (selectedDays.length() > 0) {
        // Remove trailing comma and space
        selectedDays.setLength(selectedDays.length() - 2);
    }

    return selectedDays.toString();
}
}

