/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.FacultyRole;

import Model.CourseDetails;
import Model.CourseDetailsDirectory;
import Model.StudentDetails;
import Model.StudentDetailsDirectory;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rohan
 */
public class ProfessorDashboardJPanel extends javax.swing.JPanel {
    
    private CourseDetailsDirectory coursedetailsdirectory;
    private JPanel container;
    private CourseDetails coursedetails;
    private StudentDetails studentDetails;
    private StudentDetailsDirectory studentDetailsDirectory;
    private javax.swing.JTable tableCourseCatalog;

    /**
     * Creates new form FacultyDashboardJPanel
     */
//    public ProfessorDashboardJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JTextField textProfessorLoginPassword, JTextField textProfessorLoginUsername, CourseDetails coursedetails) {
//        
//        
//        
//    }

//    ProfessorDashboardJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JTextField textProfessorLoginPassword, JTextField textProfessorLoginUsername) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    public ProfessorDashboardJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField PasswordFieldProfessor, JTextField textProfessorLoginUsername, CourseDetails coursedetails, StudentDetailsDirectory studentDetailsDirectory) {
        initComponents();
        
        this.coursedetailsdirectory = coursedetailsdirectory;
        this.studentDetailsDirectory = studentDetailsDirectory;
//        System.out.println(this.coursedetailsdirectory);
        this.coursedetails = coursedetails;
        this.container =  container;
        tableCourseCatalog = new javax.swing.JTable();
//        System.out.println(studentDetailsDirectory);
        
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }


    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProfessorDashboard = new javax.swing.JLabel();
        buttonProfessorViewStudents = new javax.swing.JButton();
        buttonProfessorLogout = new javax.swing.JButton();
        buttonProfessorCreateCourse = new javax.swing.JButton();

        labelProfessorDashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelProfessorDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProfessorDashboard.setText("Hello Professor");
        labelProfessorDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        buttonProfessorViewStudents.setBackground(new java.awt.Color(153, 153, 153));
        buttonProfessorViewStudents.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonProfessorViewStudents.setForeground(new java.awt.Color(255, 255, 255));
        buttonProfessorViewStudents.setText("View Enrolled Students");
        buttonProfessorViewStudents.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonProfessorViewStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfessorViewStudentsActionPerformed(evt);
            }
        });

        buttonProfessorLogout.setBackground(new java.awt.Color(153, 153, 153));
        buttonProfessorLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonProfessorLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonProfessorLogout.setText("Logout");
        buttonProfessorLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfessorLogoutActionPerformed(evt);
            }
        });

        buttonProfessorCreateCourse.setBackground(new java.awt.Color(153, 153, 153));
        buttonProfessorCreateCourse.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonProfessorCreateCourse.setForeground(new java.awt.Color(255, 255, 255));
        buttonProfessorCreateCourse.setText("Create Course");
        buttonProfessorCreateCourse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        buttonProfessorCreateCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfessorCreateCourseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(400, 400, 400)
                .addComponent(buttonProfessorCreateCourse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonProfessorViewStudents)
                .addGap(314, 314, 314))
            .addComponent(labelProfessorDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(686, 686, 686)
                .addComponent(buttonProfessorLogout)
                .addContainerGap(717, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelProfessorDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProfessorViewStudents)
                    .addComponent(buttonProfessorCreateCourse))
                .addGap(48, 48, 48)
                .addComponent(buttonProfessorLogout)
                .addContainerGap(280, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProfessorCreateCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfessorCreateCourseActionPerformed
        // TODO add your handling code here:
        
        ProfessorCourseCreationJPanel courseCreate= new ProfessorCourseCreationJPanel(container,coursedetailsdirectory,coursedetails);
        container.add("ProfessorDashboardJPanel", courseCreate);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
//        this.coursedetailsdirectory=coursedetailsdirectory;
        
    }//GEN-LAST:event_buttonProfessorCreateCourseActionPerformed

    private void buttonProfessorLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfessorLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonProfessorLogoutActionPerformed

    private void buttonProfessorViewStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfessorViewStudentsActionPerformed
        // TODO add your handling code here:
        
        ViewEnrolledStudentsJPanel panel = new ViewEnrolledStudentsJPanel(container,studentDetailsDirectory,studentDetails);
        container.add("ViewEnrolledStudentsJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        System.out.println(studentDetailsDirectory);
        
    }//GEN-LAST:event_buttonProfessorViewStudentsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonProfessorCreateCourse;
    private javax.swing.JButton buttonProfessorLogout;
    private javax.swing.JButton buttonProfessorViewStudents;
    private javax.swing.JLabel labelProfessorDashboard;
    // End of variables declaration//GEN-END:variables

    
    
              
        

   

    
}
