/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface;


import userManagement.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import static userInterface.SearchandUpdateUserJPanel.hashPassword;
import userManagement.Directory;

/**
 *
 * @author rohan
 */
public class ViewUserJPanel extends javax.swing.JPanel {
    
    private User user;
    private JPanel userProcessContainer;
    private Directory userDirectory;
    public JTextField txtPasswordEntered;
    public JTextField txtUsernameEntered;
   
  
    //public static JTextField txtPasswordEntered;
    //public static JTextField txtUsernameEntered; 
   
    //String enteredPassword = txtPasswordEntered.getText();
    //ViewUserLoginJPanel viewUserLoginPanel = new ViewUserJPanel(userProcessContainer,  Directory userDirectory);
    /**
     * Creates new form SearchandUpdateUserJPanel
     */
    public ViewUserJPanel(JPanel userProcessContainer,   Directory userDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userDirectory = userDirectory;
        this.user = user;
        if (user != null) {
        populateLoggedinUserDetails();
        }

        
        
    }
     public ViewUserJPanel(JPanel userProcessContainer, Directory userDirectory, JTextField passwordField, JTextField usernameField, User user) {
        initComponents();
        this.user = user; 
        this.userProcessContainer = userProcessContainer;
        this.userDirectory = userDirectory;
        txtPasswordEntered = passwordField;
        txtUsernameEntered = usernameField;
    }
     
    public ViewUserJPanel(JPanel userProcessContainer, User user) {
    initComponents();
    this.userProcessContainer = userProcessContainer;
    this.user = user;
    populateLoggedinUserDetails();
    
    
    //populateLoggedinUserDetails();
}

       
        private void populateLoggedinUserDetails() {
        String enteredPassword = hashPassword(txtPasswordEntered.getText());
        String enteredUsername = txtUsernameEntered.getText();

        User loggedInUser = userDirectory.searchEnteredUsernameandPassword(enteredUsername, enteredPassword);

        if (loggedInUser != null) {
            textUsername.setText(loggedInUser.getUsername());
            textPassword.setText(loggedInUser.getPassword());
            textNUID.setText(loggedInUser.getNUID());
            textUserID.setText(loggedInUser.getUserID());
            textName.setText(loggedInUser.getName());
            textEmail.setText(loggedInUser.getEmailID());
            textContactNumber.setText(loggedInUser.getContactNumber());
            
        textUsername.setEnabled(false);
        textPassword.setEnabled(false);
        textNUID.setEnabled(false);
        textUserID.setEnabled(false);
        textName.setEnabled(false);
        textEmail.setEnabled(false);
        textContactNumber.setEnabled(false);
        
        //btnUpdate.setEnabled(true);
        
            JOptionPane.showMessageDialog(null, "User found !!", "Information", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "User not found !!", "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    
    }
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelViewUser = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        textUsername = new javax.swing.JTextField();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        textPassword = new javax.swing.JTextField();
        labelNUID = new javax.swing.JLabel();
        textNUID = new javax.swing.JTextField();
        labelUserID = new javax.swing.JLabel();
        textUserID = new javax.swing.JTextField();
        textName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        textEmail = new javax.swing.JTextField();
        labelContactNumber = new javax.swing.JLabel();
        textContactNumber = new javax.swing.JTextField();
        buttonViewDetails = new javax.swing.JButton();

        labelViewUser.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelViewUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelViewUser.setText("View User");

        buttonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBack.setText("Back");
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        textUsername.setEnabled(false);
        textUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsernameActionPerformed(evt);
            }
        });

        labelUsername.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUsername.setText("Username :");

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPassword.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPassword.setText("Password :");

        textPassword.setEnabled(false);

        labelNUID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNUID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelNUID.setText("NUID :");

        textNUID.setEnabled(false);

        labelUserID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelUserID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUserID.setText("User ID :");

        textUserID.setEnabled(false);

        textName.setEnabled(false);

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelName.setText("Name :");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelEmail.setText("Email :");

        textEmail.setEnabled(false);

        labelContactNumber.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelContactNumber.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelContactNumber.setText("Contact Number:");

        textContactNumber.setEnabled(false);

        buttonViewDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonViewDetails.setText("View User Details");
        buttonViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(labelContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(textContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(textUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(labelViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(buttonBack)
                        .addGap(86, 86, 86)
                        .addComponent(buttonViewDetails)))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(labelViewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUsername, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNUID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonViewDetails)
                    .addComponent(buttonBack))
                .addContainerGap(99, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_buttonBackActionPerformed

    private void textUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsernameActionPerformed

    
    private void buttonViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewDetailsActionPerformed
        // TODO add your handling code here:
        populateLoggedinUserDetails();
    }//GEN-LAST:event_buttonViewDetailsActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonViewDetails;
    private javax.swing.JLabel labelContactNumber;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelNUID;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUserID;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelViewUser;
    private javax.swing.JTextField textContactNumber;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNUID;
    private javax.swing.JTextField textName;
    private javax.swing.JTextField textPassword;
    private javax.swing.JTextField textUserID;
    private javax.swing.JTextField textUsername;
    // End of variables declaration//GEN-END:variables
}
