/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.CourseDetailsDirectory;
import Model.EmployerDetails;
import UserInterface.WorkAreas.EmployerRole.EmployerDashboardJPanel;
import Model.CourseDetails;
import Model.StudentDetailsDirectory;
//import UserInterface.WorkAreas.EmployerRole.EmployerDashboardJPanel1;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JPasswordField;


/**
 *
 * @author rohan
 */
public class EmployerLoginJPanel extends javax.swing.JPanel {
    
    private EmployerDetails employerdetails;
    private JPanel container;
    private javax.swing.JTable tblCourseCatalog;
    private CourseDetails courseDetails;
    private StudentDetailsDirectory studentDetailsDirectory;
    private CourseDetailsDirectory coursedetailsdirectory;

    /**
     * Creates new form StudentLoginJPanel
     * @param container
     */
    
    public EmployerLoginJPanel(JPanel container, JPasswordField textEmployerLoginPassword, JTextField textEmployerLoginUsername, EmployerDetails employerdetails,CourseDetails courseDetails, StudentDetailsDirectory studentDetailsDirectory,CourseDetailsDirectory courseDetailsDirectory) {
        initComponents();
        
 
//        this.employerdetails = new EmployerDetails();
        this.container=container;
        this.courseDetails=courseDetails;
        this.coursedetailsdirectory=courseDetailsDirectory;
        this.studentDetailsDirectory=studentDetailsDirectory;
//        System.out.println(this.studentDetailsDirectory);
          
    }

//    EmployerLoginJPanel(JPanel container, JTextField textEmployerLoginPassword, JTextField textEmployerLoginUsername) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEmployerLogin = new javax.swing.JLabel();
        labelEmployerLoginUsername = new javax.swing.JLabel();
        labelEmployerLoginPassword = new javax.swing.JLabel();
        textEmployerLoginUsername = new javax.swing.JTextField();
        buttonEmployerLoginSubmit = new javax.swing.JButton();
        textEmployerLoginPassword = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        labelEmployerLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelEmployerLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelEmployerLogin.setText("Employer Login");
        labelEmployerLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        labelEmployerLoginUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelEmployerLoginUsername.setText("Username:");
        labelEmployerLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelEmployerLoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelEmployerLoginPassword.setText("Password:");
        labelEmployerLoginPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        textEmployerLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        buttonEmployerLoginSubmit.setBackground(new java.awt.Color(153, 153, 153));
        buttonEmployerLoginSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buttonEmployerLoginSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonEmployerLoginSubmit.setText("Login");
        buttonEmployerLoginSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buttonEmployerLoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEmployerLoginSubmitActionPerformed(evt);
            }
        });

        textEmployerLoginPassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelEmployerLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmployerLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmployerLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textEmployerLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textEmployerLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(558, 558, 558)
                        .addComponent(buttonEmployerLoginSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(515, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelEmployerLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmployerLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmployerLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmployerLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textEmployerLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(buttonEmployerLoginSubmit)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonEmployerLoginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEmployerLoginSubmitActionPerformed
        // TODO add your handling code here:
        
        String enteredUsername = textEmployerLoginUsername.getText();
        String enteredPassword = textEmployerLoginPassword.getText();
        
        if ((enteredPassword!=null && enteredPassword.equals("Employer123")) || (enteredUsername!=null && enteredUsername.equals("Employer")))
       
        {
            
            EmployerDashboardJPanel panel = new EmployerDashboardJPanel(container,textEmployerLoginPassword, textEmployerLoginUsername, employerdetails,coursedetailsdirectory,courseDetails,studentDetailsDirectory);
            container.add("EmployerDashboardJPanel", panel);
            CardLayout layout =(CardLayout) container.getLayout();
            layout.next(container); 
            
        }
        
        else
            
        {
            
            JOptionPane.showMessageDialog(null, "Incorrect Username or Password Entered!", "Information", JOptionPane.INFORMATION_MESSAGE);
           
        }
      
    }//GEN-LAST:event_buttonEmployerLoginSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEmployerLoginSubmit;
    private javax.swing.JLabel labelEmployerLogin;
    private javax.swing.JLabel labelEmployerLoginPassword;
    private javax.swing.JLabel labelEmployerLoginUsername;
    private javax.swing.JPasswordField textEmployerLoginPassword;
    private javax.swing.JTextField textEmployerLoginUsername;
    // End of variables declaration//GEN-END:variables
}
