/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import UserInterface.WorkAreas.FacultyRole.ProfessorDashboardJPanel;
import Model.CourseDetails;
import Model.CourseDetailsDirectory;
//import Model.CourseDetails;
//import Model.StudentDetailsDirectory;
import Model.EmployerDetails;
import java.awt.CardLayout;
import Model.StudentDetails;
import javax.swing.JPasswordField;
import Model.StudentDetailsDirectory;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author rohan
 */
public class Home extends javax.swing.JFrame {
    
    private CourseDetailsDirectory coursedetailsdirectory;
    private StudentDetailsDirectory studentDetailsDirectory;
    private CourseDetails coursedetails;
    private StudentDetails studentdetails;
    private javax.swing.JTable tableCourseCatalog;
    private EmployerDetails employerdetails;
    private JTable tbltranscripts;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.coursedetailsdirectory = new CourseDetailsDirectory();
        this.studentDetailsDirectory = new StudentDetailsDirectory();
        this.employerdetails = new EmployerDetails();
        this.tbltranscripts = new JTable();
        
        this.coursedetails = new CourseDetails();
        tableCourseCatalog = new javax.swing.JTable();
        
//        System.out.println(this.coursedetails);
//        System.out.println(this.studentDetailsDirectory);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        topJPanel = new javax.swing.JPanel();
        buttonAdminLogin = new javax.swing.JButton();
        buttonProfessorLogin = new javax.swing.JButton();
        buttonStudentLogin = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        topJPanel.setBackground(new java.awt.Color(255, 255, 255));
        topJPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        topJPanel.setPreferredSize(new java.awt.Dimension(1373, 100));

        buttonAdminLogin.setBackground(new java.awt.Color(153, 153, 153));
        buttonAdminLogin.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        buttonAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonAdminLogin.setText("Admin Login");
        buttonAdminLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buttonAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdminLoginActionPerformed(evt);
            }
        });

        buttonProfessorLogin.setBackground(new java.awt.Color(153, 153, 153));
        buttonProfessorLogin.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        buttonProfessorLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonProfessorLogin.setText("Professor Login");
        buttonProfessorLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buttonProfessorLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfessorLoginActionPerformed(evt);
            }
        });

        buttonStudentLogin.setBackground(new java.awt.Color(153, 153, 153));
        buttonStudentLogin.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        buttonStudentLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonStudentLogin.setText("Student Login");
        buttonStudentLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buttonStudentLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout topJPanelLayout = new javax.swing.GroupLayout(topJPanel);
        topJPanel.setLayout(topJPanelLayout);
        topJPanelLayout.setHorizontalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(buttonAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(buttonProfessorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(127, 127, 127)
                .addComponent(buttonStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        topJPanelLayout.setVerticalGroup(
            topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topJPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(topJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonProfessorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(185, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(topJPanel);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdminLoginActionPerformed
        // TODO add your handling code here:
        
        JTextField textEmployerLoginUsername = new JTextField();
        JTextField textEmployerLoginPassword = new JPasswordField();
        
        EmployerLoginJPanel panel= new EmployerLoginJPanel(container, (JPasswordField) textEmployerLoginPassword,textEmployerLoginUsername,employerdetails,coursedetails,studentDetailsDirectory,coursedetailsdirectory);
        container.add("EmployerLoginJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_buttonAdminLoginActionPerformed

    private void buttonProfessorLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfessorLoginActionPerformed
        // TODO add your handling code here:
        
     JTextField textProfessorLoginUsername = new JTextField();
     JTextField textProfessorLoginPassword = new JPasswordField();
     
     
//     ProfessorLoginJPanel panel=new ProfessorLoginJPanel(container,textProfessorLoginUsername,textProfessorLoginPassword,coursedetails);
//     container.add("ProfessorLoginJPanel", panel);
//     CardLayout layout = (CardLayout) container.getLayout();
//     layout.next(container);
     
     ProfessorLoginJPanel panel = new ProfessorLoginJPanel(container, coursedetailsdirectory, (JPasswordField) textProfessorLoginPassword, textProfessorLoginUsername, coursedetails,studentDetailsDirectory);
     
     container.add("ProfessorLoginJPanel", panel);
     CardLayout layout = (CardLayout) container.getLayout();
     layout.next(container);
        
    
    }//GEN-LAST:event_buttonProfessorLoginActionPerformed

    private void buttonStudentLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentLoginActionPerformed
        // TODO add your handling code here:
        JTextField textStudentUsername = new JTextField();
        JTextField textStudentLoginPassword = new JPasswordField();
        
        StudentLoginJPanel panel= new StudentLoginJPanel(container, coursedetailsdirectory,(JPasswordField) textStudentLoginPassword,textStudentUsername,coursedetails,studentDetailsDirectory,tbltranscripts);
        container.add("StudentLoginJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_buttonStudentLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAdminLogin;
    private javax.swing.JButton buttonProfessorLogin;
    private javax.swing.JButton buttonStudentLogin;
    private javax.swing.JPanel container;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel topJPanel;
    // End of variables declaration//GEN-END:variables
}
