/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.CourseDetails;
import Model.CourseDetailsDirectory;
import Model.StudentDetails;
import Model.StudentDetailsDirectory;
import UserInterface.WorkAreas.FacultyRole.ProfessorDashboardJPanel;
import UserInterface.WorkAreas.StudentRole.StudentDashboardJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author rohan
 */
public class StudentLoginJPanel extends javax.swing.JPanel {

    private final CourseDetailsDirectory coursedetailsdirectory;
    private final CourseDetails coursedetails;
    private final JPanel container;
    private final StudentDetailsDirectory studentDetailsDirectory;
    private StudentDetails studentDetails;
    private JTable tbltranscripts;

    /**
     * Creates new form StudentLoginJPanel
     */
//    public StudentLoginJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField PasswordFieldProfessor, JTextField textProfessorLoginUsername, CourseDetails coursedetails) {
//        initComponents();
////        CourseDetailsDirectory CourseDetailsDirectory;
//        this.coursedetailsdirectory = coursedetailsdirectory;
//        this.coursedetails = coursedetails;
//        this.container=container;
//        System.out.println(this.coursedetails);
//        System.out.println(this.coursedetailsdirectory);
//        
//    }

//    StudentLoginJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField jPasswordField, JTextField textStudentUsername, CourseDetails coursedetails, StudentDetailsDirectory studentDetailsDirectory) {
//        
////        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

//    StudentLoginJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField jPasswordField, JTextField textStudentUsername, CourseDetails coursedetails, StudentDetailsDirectory studentDetailsDirectory, StudentDetails studentdetails) {
//       
////        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

    StudentLoginJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField jPasswordField, JTextField textStudentUsername, CourseDetails coursedetails, StudentDetailsDirectory studentDetailsDirectory,JTable tbltranscripts) {
         initComponents();
//        CourseDetailsDirectory CourseDetailsDirectory;
        this.coursedetailsdirectory = coursedetailsdirectory;
        this.coursedetails = coursedetails;
        this.studentDetailsDirectory=studentDetailsDirectory;
//        System.out.println(this.studentDetailsDirectory);
        this.tbltranscripts=tbltranscripts;
        this.container=container;
//        System.out.println(this.coursedetails);
//        System.out.println(this.tbltranscripts);
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelStudentLogin = new javax.swing.JLabel();
        labelStudentLoginUsername = new javax.swing.JLabel();
        labelStudentLoginPassword = new javax.swing.JLabel();
        textStudentLoginUsername = new javax.swing.JTextField();
        buttonStudentLoginSubmit = new javax.swing.JButton();
        PasswordFieldStudent = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        labelStudentLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelStudentLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStudentLogin.setText("Student Login");
        labelStudentLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        labelStudentLoginUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelStudentLoginUsername.setText("Username:");
        labelStudentLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelStudentLoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelStudentLoginPassword.setText("Password:");
        labelStudentLoginPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        textStudentLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        buttonStudentLoginSubmit.setBackground(new java.awt.Color(153, 153, 153));
        buttonStudentLoginSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buttonStudentLoginSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonStudentLoginSubmit.setText("Login");
        buttonStudentLoginSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buttonStudentLoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentLoginSubmitActionPerformed(evt);
            }
        });

        PasswordFieldStudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelStudentLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1443, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelStudentLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelStudentLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textStudentLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFieldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(buttonStudentLoginSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(437, 437, 437))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(labelStudentLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStudentLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textStudentLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStudentLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordFieldStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(buttonStudentLoginSubmit)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStudentLoginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentLoginSubmitActionPerformed
        // TODO add your handling code here:
        String enteredUsername = textStudentLoginUsername.getText();
        String enteredPassword = PasswordFieldStudent.getText();
        
        if ((enteredPassword!=null && enteredPassword.equals("Student123")) || (enteredUsername!=null && enteredUsername.equals("Student")))
       
        {
            
            StudentDashboardJPanel panel = new StudentDashboardJPanel(container, coursedetailsdirectory, PasswordFieldStudent, textStudentLoginUsername, coursedetails,studentDetailsDirectory,tbltranscripts);
            container.add("StudentDashboardJPanel", panel);
            CardLayout layout =(CardLayout) container.getLayout();
            layout.next(container);  
        }
        
        else
            
        {
            
            JOptionPane.showMessageDialog(null, "Incorrect Username or Password Entered!", "Information", JOptionPane.INFORMATION_MESSAGE);
           
        }
    }//GEN-LAST:event_buttonStudentLoginSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordFieldStudent;
    private javax.swing.JButton buttonStudentLoginSubmit;
    private javax.swing.JLabel labelStudentLogin;
    private javax.swing.JLabel labelStudentLoginPassword;
    private javax.swing.JLabel labelStudentLoginUsername;
    private javax.swing.JTextField textStudentLoginUsername;
    // End of variables declaration//GEN-END:variables
}
