/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.EmployerRole;

import Model.CourseDetails;
import Model.CourseDetailsDirectory;
import Model.StudentDetails;
import Model.StudentDetailsDirectory;
import UserInterface.WorkAreas.StudentRole.StudentViewCoursesJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rohan
 */
public class EmployerSearchAndRateJPanel extends javax.swing.JPanel {

    private JPanel container;
    private CourseDetails coursedetails;
    private CourseDetailsDirectory courseDetailsDirectory;
    private StudentDetailsDirectory studentdetailsdirectory;
    private CourseDetails selectedProfessor;
//    private CourseDetailsDirectory coursedetailsdirectory;
    
    /*public EmployerSearchAndRateJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, CourseDetails coursedetails, StudentDetailsDirectory studentdetailsdirectory) {
        initComponents();
        this.container = container;
        this.courseDetailsDirectory = coursedetailsdirectory;
        this.coursedetails = coursedetails;
        this.studentdetailsdirectory=studentdetailsdirectory;
    }*/

//    EmployerSearchAndRateJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, CourseDetails coursedetails, StudentDetailsDirectory studentdetailsdirectory) {
//        //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//      
//    }

//    EmployerSearchAndRateJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, CourseDetails coursedetails, StudentDetailsDirectory studentdetailsdirectory,CourseDetailsDirectory courseDetailsDirectory) {
//       //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//          
//    }

    EmployerSearchAndRateJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, CourseDetails coursedetails, StudentDetailsDirectory studentdetailsdirectory) {
        
        initComponents();
        this.container = container;
        this.courseDetailsDirectory = coursedetailsdirectory;
        this.coursedetails = coursedetails;
        this.studentdetailsdirectory=studentdetailsdirectory;  
//        System.out.println(this.courseDetailsDirectory);
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtSearchProfessorName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProfessorSearched = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtRating = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnSearchProfessor = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Search and Rate Professor:");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Professor Name :");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtSearchProfessorName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtSearchProfessorName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchProfessorNameActionPerformed(evt);
            }
        });

        tblProfessorSearched.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Professor Name:", "Course Name:", "Course Code:", "Intake:", "Rating:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblProfessorSearched);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Enter Rating:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        txtRating.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        txtRating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRatingActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setText("Save ");
        btnSave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnSearchProfessor.setText("Search");
        btnSearchProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(437, 437, 437))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(688, 688, 688))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 717, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(506, 506, 506)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(txtSearchProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 358, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRating, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchProfessorNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchProfessorNameActionPerformed
           
    }//GEN-LAST:event_txtSearchProfessorNameActionPerformed

    private void txtRatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRatingActionPerformed

    private void btnSearchProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProfessorActionPerformed
    String professorName = txtSearchProfessorName.getText().trim();
    CourseDetails prf = courseDetailsDirectory.searchProfessorName(professorName);

    if (prf != null) {
        selectedProfessor = prf; // Store the selected professor
        populateTable1(prf); // Pass the professor to the populateTable method
    } else {
        JOptionPane.showMessageDialog(null, "Professor does not exist", "Information", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnSearchProfessorActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        if (selectedProfessor != null) {
        int rating = Integer.parseInt(txtRating.getText());
        selectedProfessor.setProfessorRating(rating);
        populateTable1(selectedProfessor); // Pass the updated professor to the populateTable method
    } else {
        JOptionPane.showMessageDialog(null, "Please search for a professor first.", "Information", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProfessorSearched;
    private javax.swing.JTextField txtRating;
    private javax.swing.JTextField txtSearchProfessorName;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    

        DefaultTableModel dtm = (DefaultTableModel) tblProfessorSearched.getModel();
        dtm.setRowCount(0);
        for (CourseDetails prf : courseDetailsDirectory.getCourseList()) {
            Object[] row = new Object[4];
            row[0]= prf.getProfessorName();
            row[1]= prf.getCourseName();
            row[2]= prf.getCourseCode();
            row[3]= prf.getIntake();
            //row[4]= prf.getProfessorRating();
            dtm.addRow(row);    
        }
      
    }

    private void populateTable1(CourseDetails prf) {
       // throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    
    DefaultTableModel dtm = (DefaultTableModel) tblProfessorSearched.getModel();
    dtm.setRowCount(0);

    if (selectedProfessor != null) {
        Object[] row = new Object[5]; // Include the rating column
        row[0] = selectedProfessor.getProfessorName();
        row[1] = selectedProfessor.getCourseName();
        row[2] = selectedProfessor.getCourseCode();
        row[3] = selectedProfessor.getIntake();
        row[4] = selectedProfessor.getProfessorRating(); // Rating column
        dtm.addRow(row);
    }
}
    }

