/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Model.CourseDetails;
import Model.CourseDetailsDirectory;
import Model.StudentDetailsDirectory;
import Model.StudentDetails;
import javax.swing.JPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author rohan
 */
public class StudentViewCoursesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ProfessorCourseCreationJPanel
     */
    private JPanel container;
    private CourseDetails cd;
    private CourseDetails coursedetails;
    private StudentDetails studentdetails;
    private CourseDetailsDirectory coursedetailsdirectory;
    private CourseDetailsDirectory courseDetailsDirectory;
    private StudentDetailsDirectory studentdetailsdirectory;
    
    
//    private javax.swing.AbstractAction.JTable tblCourseCatalogue;
    //private CourseDetailsDirectory coursedirectory;
    //private CourseDetailsDirectory coursedetailsdirectory;
    private String courseName;
    private String professorName;


    StudentViewCoursesJPanel(JPanel container, CourseDetails cd, StudentDetailsDirectory studentdetailsdirectory, CourseDetailsDirectory courseDetailsDirectory) {
        initComponents();
        this.container = container;
        this.coursedetails = cd;
//        System.out.println(studentDetailsDirectory);
//        this.studentdetails = studentdetails;
        this.courseDetailsDirectory = courseDetailsDirectory;
//        StudentDetailsDirectory studentDetailsDirectory = null;
        
        
        this.studentdetailsdirectory = studentdetailsdirectory;
//        System.out.println(this.studentdetailsdirectory);
//        System.out.println(studentdetailsdirectory);
        
  
        populateCourseDetails();
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelViewCourseTitle = new javax.swing.JLabel();
        labelCourseCode = new javax.swing.JLabel();
        labelCourseName = new javax.swing.JLabel();
        labelIntake = new javax.swing.JLabel();
        labelScheduleDays = new javax.swing.JLabel();
        labelScheduleTime = new javax.swing.JLabel();
        txtCourseCode = new javax.swing.JTextField();
        txtCourseName = new javax.swing.JTextField();
        buttonRegister = new javax.swing.JButton();
        labelCourseDescription = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCourseDescription = new javax.swing.JTextArea();
        labelMode = new javax.swing.JLabel();
        buttonBack = new javax.swing.JButton();
        buttonLogout = new javax.swing.JButton();
        labelProfessorName = new javax.swing.JLabel();
        txtProfessorName = new javax.swing.JTextField();
        txtMode = new javax.swing.JTextField();
        txtIntake = new javax.swing.JTextField();
        txtCourseSchedule = new javax.swing.JTextField();
        txtCourseTime = new javax.swing.JTextField();
        labelStudentName = new javax.swing.JLabel();
        txtStudentName = new javax.swing.JTextField();
        buttonView = new javax.swing.JButton();
        labelProfessorRating = new javax.swing.JLabel();
        txtProfessorRating = new javax.swing.JTextField();

        labelViewCourseTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelViewCourseTitle.setText("View Course");

        labelCourseCode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCourseCode.setText("Course Code:");

        labelCourseName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCourseName.setText("Course Name:");

        labelIntake.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelIntake.setText("Intake:");

        labelScheduleDays.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelScheduleDays.setText("Course Schedule (Days):");

        labelScheduleTime.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelScheduleTime.setText("Course Schedule (Time):");

        txtCourseCode.setEditable(false);

        txtCourseName.setEditable(false);

        buttonRegister.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonRegister.setText("Register");
        buttonRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterActionPerformed(evt);
            }
        });

        labelCourseDescription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelCourseDescription.setText("Course Description:");

        txtCourseDescription.setEditable(false);
        txtCourseDescription.setColumns(20);
        txtCourseDescription.setRows(5);
        jScrollPane1.setViewportView(txtCourseDescription);

        labelMode.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelMode.setText("Mode:");

        buttonBack.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonBack.setText("<- Back ");
        buttonBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });

        buttonLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonLogout.setText("Logout");
        buttonLogout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelProfessorName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProfessorName.setText("Professor Name:");

        txtProfessorName.setEditable(false);

        txtMode.setEditable(false);

        txtIntake.setEditable(false);

        txtCourseSchedule.setEditable(false);

        txtCourseTime.setEditable(false);

        labelStudentName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelStudentName.setText("Student Name:");

        txtStudentName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStudentNameActionPerformed(evt);
            }
        });

        buttonView.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonView.setText("View");
        buttonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonViewActionPerformed(evt);
            }
        });

        labelProfessorRating.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelProfessorRating.setText("Professor Rating:");

        txtProfessorRating.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(buttonBack)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(885, 885, 885)
                                .addComponent(buttonLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(448, 448, 448)
                                .addComponent(labelViewCourseTitle))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelScheduleTime, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelScheduleDays, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelProfessorRating, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                                    .addComponent(txtCourseCode)
                                    .addComponent(txtCourseName)
                                    .addComponent(txtIntake)
                                    .addComponent(txtCourseSchedule)
                                    .addComponent(txtCourseTime, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtStudentName)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(labelMode, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMode, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(221, 221, 221)
                                .addComponent(txtProfessorRating))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(buttonRegister)
                        .addGap(98, 98, 98)
                        .addComponent(buttonView)))
                .addContainerGap(312, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(buttonLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(buttonBack)))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelViewCourseTitle)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelMode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelProfessorName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfessorRating, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtProfessorRating, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseCode, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCourseName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelScheduleDays, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCourseTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelScheduleTime, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(labelCourseDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelStudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRegister)
                    .addComponent(buttonView))
                .addContainerGap(68, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterActionPerformed
         
// TODO add your handling code here:

               String mode = txtMode.getText();
               
               String coursecode = txtCourseCode.getText();
               String coursename = txtCourseName.getText();
               String intake = txtIntake.getText();
               String coursedescription = txtCourseDescription.getText();
               String professorName = txtProfessorName.getText();
               String scheduledDate = txtCourseSchedule.getText();
               String scheduledTime = txtCourseTime.getText();
               String studentName = txtStudentName.getText();
               
               StudentDetails sd = studentdetailsdirectory.addStudentCourse();
        
        sd.setMode(mode);
        sd.setStudentName(studentName);
        sd.setCourseCode(coursecode);
        sd.setCourseName(coursename);
        sd.setIntake(intake);
        sd.setCourseScheduleDate(scheduledDate);
        sd.setCourseDescription(coursedescription);
        sd.setCourseScheduleTime(scheduledTime);
//        System.out.println();
        
        
        JOptionPane.showMessageDialog(null,"Course added Successfully !");
               
    }//GEN-LAST:event_buttonRegisterActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout=(CardLayout) container.getLayout();
        layout.previous(container); 
    }//GEN-LAST:event_buttonBackActionPerformed

    private void txtStudentNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStudentNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStudentNameActionPerformed

    private void buttonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonViewActionPerformed
        // TODO add your handling code here:
        DisplayRegisteredCoursesJPanel panel = new DisplayRegisteredCoursesJPanel (container,studentdetails,studentdetailsdirectory,courseDetailsDirectory);
        container.add("DisplayRegisteredCoursesJPanel",panel);
        CardLayout layout = (CardLayout)container.getLayout();
        layout.next(container);  
    }//GEN-LAST:event_buttonViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBack;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton buttonRegister;
    private javax.swing.JButton buttonView;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCourseCode;
    private javax.swing.JLabel labelCourseDescription;
    private javax.swing.JLabel labelCourseName;
    private javax.swing.JLabel labelIntake;
    private javax.swing.JLabel labelMode;
    private javax.swing.JLabel labelProfessorName;
    private javax.swing.JLabel labelProfessorRating;
    private javax.swing.JLabel labelScheduleDays;
    private javax.swing.JLabel labelScheduleTime;
    private javax.swing.JLabel labelStudentName;
    private javax.swing.JLabel labelViewCourseTitle;
    private javax.swing.JTextField txtCourseCode;
    private javax.swing.JTextArea txtCourseDescription;
    private javax.swing.JTextField txtCourseName;
    private javax.swing.JTextField txtCourseSchedule;
    private javax.swing.JTextField txtCourseTime;
    private javax.swing.JTextField txtIntake;
    private javax.swing.JTextField txtMode;
    private javax.swing.JTextField txtProfessorName;
    private javax.swing.JTextField txtProfessorRating;
    private javax.swing.JTextField txtStudentName;
    // End of variables declaration//GEN-END:variables


    private void populateCourseDetails() {
        txtMode.setText(coursedetails.getMode());
        txtProfessorName.setText(coursedetails.getProfessorName());
        txtCourseCode.setText(coursedetails.getCourseCode());
        txtCourseName.setText(coursedetails.getCourseName());
        txtIntake.setText(coursedetails.getIntake());
        txtCourseSchedule.setText(coursedetails.getCourseScheduleDate());
        txtCourseTime.setText(coursedetails.getCourseTime());
        txtCourseDescription.setText(coursedetails.getCourseDescription());
        txtProfessorRating.setText(String.valueOf(coursedetails.getProfessorRating()));

//        txtProfessorRating.setText(coursedetails.getProfessorRating());
        
    }
    }




