/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.WorkAreas.StudentRole;

import Model.CourseDetails;
import Model.CourseDetailsDirectory;
import Model.EmployerDetails;
import Model.StudentDetails;
import Model.StudentDetailsDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author rohan
 */
public class StudentDashboardJPanel extends javax.swing.JPanel {
    private CourseDetailsDirectory coursedetailsdirectory;
    private StudentDetailsDirectory studentdetailsdirectory;
    private JPanel container;
    private CourseDetails coursedetails;
    private javax.swing.JTable tblCourseCatalog;
    private EmployerDetails employerdetails;
//    private CourseDetails coursedetails;
    private JTable tbltranscripts;
    private StudentDetails sd;
    

    /**
     * Creates new form StudentDashboardJPanel
     */
//    public StudentDashboardJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField PasswordFieldStudent, JTextField textStudentLoginUsername, CourseDetails coursedetails) {
//        
//    }

//    public StudentDashboardJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JTextField PasswordFieldStudent, JTextField textStudentLoginUsername) {
//       //throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//    }

//    public StudentDashboardJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField PasswordFieldStudent, JTextField textStudentLoginUsername, CourseDetails coursedetails, StudentDetailsDirectory studentDetailsDirectory, StudentDetails studentDetails) {
////        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
//        
//    }

    public StudentDashboardJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField PasswordFieldStudent, JTextField textStudentLoginUsername, CourseDetails coursedetails, StudentDetailsDirectory studentDetailsDirectory,JTable tbltranscripts) {
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        initComponents();
        this.coursedetailsdirectory = coursedetailsdirectory;
        this.coursedetails = coursedetails;
        this.container =  container;
        this.studentdetailsdirectory=studentDetailsDirectory;
        this.employerdetails= employerdetails;
        this.tbltranscripts=tbltranscripts;
//        System.out.println(this.studentdetailsdirectory);
       
//        System.out.println(this.coursedetails);
//        System.out.println(this.studentdetailsdirectory);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonStudentCourseRegistration = new javax.swing.JButton();
        buttonStudentViewTranscript = new javax.swing.JButton();
        buttonStudentDeclareGraduation = new javax.swing.JButton();
        buttonStudentLogout = new javax.swing.JButton();
        labelStudentDashboard = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        buttonStudentCourseRegistration.setBackground(new java.awt.Color(153, 153, 153));
        buttonStudentCourseRegistration.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonStudentCourseRegistration.setForeground(new java.awt.Color(255, 255, 255));
        buttonStudentCourseRegistration.setText("Course Registration");
        buttonStudentCourseRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentCourseRegistrationActionPerformed(evt);
            }
        });

        buttonStudentViewTranscript.setBackground(new java.awt.Color(153, 153, 153));
        buttonStudentViewTranscript.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonStudentViewTranscript.setForeground(new java.awt.Color(255, 255, 255));
        buttonStudentViewTranscript.setText("View Transcript");

        buttonStudentDeclareGraduation.setBackground(new java.awt.Color(153, 153, 153));
        buttonStudentDeclareGraduation.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonStudentDeclareGraduation.setForeground(new java.awt.Color(255, 255, 255));
        buttonStudentDeclareGraduation.setText("Declare Graduation");
        buttonStudentDeclareGraduation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentDeclareGraduationActionPerformed(evt);
            }
        });

        buttonStudentLogout.setBackground(new java.awt.Color(153, 153, 153));
        buttonStudentLogout.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonStudentLogout.setForeground(new java.awt.Color(255, 255, 255));
        buttonStudentLogout.setText("Logout");
        buttonStudentLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStudentLogoutActionPerformed(evt);
            }
        });

        labelStudentDashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelStudentDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStudentDashboard.setText("Hello Student");
        labelStudentDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelStudentDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(buttonStudentCourseRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 396, Short.MAX_VALUE)
                .addComponent(buttonStudentDeclareGraduation)
                .addGap(365, 365, 365))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonStudentViewTranscript)
                        .addGap(677, 677, 677))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonStudentLogout)
                        .addGap(289, 289, 289))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStudentDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonStudentCourseRegistration)
                    .addComponent(buttonStudentDeclareGraduation))
                .addGap(66, 66, 66)
                .addComponent(buttonStudentViewTranscript)
                .addGap(53, 53, 53)
                .addComponent(buttonStudentLogout)
                .addContainerGap(266, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStudentLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonStudentLogoutActionPerformed

    private void buttonStudentCourseRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentCourseRegistrationActionPerformed
        // TODO add your handling code here:
        StudentBrowseCoursesJPanel panel= new StudentBrowseCoursesJPanel(container,coursedetailsdirectory,coursedetails,studentdetailsdirectory);
        container.add("StudentBrowseCoursesJPanel", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
        
    }//GEN-LAST:event_buttonStudentCourseRegistrationActionPerformed

    private void buttonStudentDeclareGraduationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStudentDeclareGraduationActionPerformed
        // TODO add your handling code here:
        StudentGradDeclaration panel= new StudentGradDeclaration(container,coursedetailsdirectory,coursedetails,studentdetailsdirectory,employerdetails,tbltranscripts,sd);
        container.add("StudentGradDeclaration", panel);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.next(container);
    }//GEN-LAST:event_buttonStudentDeclareGraduationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonStudentCourseRegistration;
    private javax.swing.JButton buttonStudentDeclareGraduation;
    private javax.swing.JButton buttonStudentLogout;
    private javax.swing.JButton buttonStudentViewTranscript;
    private javax.swing.JLabel labelStudentDashboard;
    // End of variables declaration//GEN-END:variables
}
