/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.VehicleRegistration;
import javax.swing.JOptionPane;

/**
 *
 * @author rohan
 */
public class CreateVehicleRegistrationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateVehicleRegistrationJPanel
     */
    
    VehicleRegistration regn1;
    public CreateVehicleRegistrationJPanel(VehicleRegistration paramRegn) {
        initComponents();
        this.regn1=paramRegn;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelCarManufacturer = new javax.swing.JLabel();
        labelModel = new javax.swing.JLabel();
        labelSerialNumber = new javax.swing.JLabel();
        labelFuelType = new javax.swing.JLabel();
        textCarManufacturer = new javax.swing.JTextField();
        textModel = new javax.swing.JTextField();
        textSerialNumber = new javax.swing.JTextField();
        textFuelType = new javax.swing.JTextField();
        buttonSave1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Vehicle Registration");

        labelCarManufacturer.setText("Car Manufacturer");

        labelModel.setText("Model");

        labelSerialNumber.setText("Serial Number");

        labelFuelType.setText("Fuel Type");

        buttonSave1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSave1.setText("Save");
        buttonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(286, 286, 286)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelModel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCarManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelFuelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textModel, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                            .addComponent(textCarManufacturer)
                            .addComponent(textSerialNumber)
                            .addComponent(textFuelType))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 190, Short.MAX_VALUE)
                        .addComponent(buttonSave1)))
                .addGap(209, 209, 209))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCarManufacturer)
                    .addComponent(textCarManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelModel)
                            .addComponent(textModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(buttonSave1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSerialNumber)
                    .addComponent(textSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFuelType)
                    .addComponent(textFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(198, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSave1ActionPerformed
        // TODO add your handling code here:
        
        regn1.setCarManufacturer(textCarManufacturer.getText());
        regn1.setModel(textModel.getText());
        regn1.setSerialNumber(textSerialNumber.getText());
        regn1.setFuelType(textFuelType.getText());
        
        JOptionPane.showMessageDialog(this, "Vehicle Information Saved");
        
    }//GEN-LAST:event_buttonSave1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCarManufacturer;
    private javax.swing.JLabel labelFuelType;
    private javax.swing.JLabel labelModel;
    private javax.swing.JLabel labelSerialNumber;
    private javax.swing.JTextField textCarManufacturer;
    private javax.swing.JTextField textFuelType;
    private javax.swing.JTextField textModel;
    private javax.swing.JTextField textSerialNumber;
    // End of variables declaration//GEN-END:variables
}
