/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Patient;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author rohan
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientJPanel
     */
    
    Patient patient1;
    
    public CreatePatientJPanel(Patient paramPatient) {
        initComponents();
        this.patient1=paramPatient;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCreatePatient = new javax.swing.JLabel();
        labelPatientID = new javax.swing.JLabel();
        labelPrimaryDoctor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelPatientName = new javax.swing.JLabel();
        textPatientName = new javax.swing.JTextField();
        textPatientID = new javax.swing.JTextField();
        textPrimaryDoctor = new javax.swing.JTextField();
        dropdownOnMedication = new javax.swing.JComboBox<>();
        dropdownAllergies = new javax.swing.JComboBox<>();
        buttonSave1 = new javax.swing.JButton();

        labelCreatePatient.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelCreatePatient.setText("Patient");

        labelPatientID.setText("Patient ID");

        labelPrimaryDoctor.setText("Primary Doctor");

        jLabel3.setText("On Medication");

        jLabel4.setText("Allergies");

        labelPatientName.setText("Patient Name");

        dropdownOnMedication.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Yes", "No", " " }));
        dropdownOnMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropdownOnMedicationActionPerformed(evt);
            }
        });

        dropdownAllergies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Yes", "No", " " }));

        buttonSave1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonSave1.setText("Save");
        buttonSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSave1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(labelCreatePatient))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPatientName)
                            .addComponent(labelPatientID)
                            .addComponent(labelPrimaryDoctor)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textPrimaryDoctor)
                            .addComponent(textPatientName)
                            .addComponent(textPatientID)
                            .addComponent(dropdownOnMedication, 0, 150, Short.MAX_VALUE)
                            .addComponent(dropdownAllergies, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                        .addComponent(buttonSave1)))
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(labelCreatePatient)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPatientName)
                    .addComponent(textPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPatientID)
                    .addComponent(textPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPrimaryDoctor)
                            .addComponent(textPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(buttonSave1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dropdownOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dropdownAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(173, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dropdownOnMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropdownOnMedicationActionPerformed

      
// TODO add your handling code here:
    }//GEN-LAST:event_dropdownOnMedicationActionPerformed

    private void buttonSave1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSave1ActionPerformed
        // TODO add your handling code here:
        
        patient1.setPatientName(textPatientName.getText());
        patient1.setPatientID(textPatientID.getText());
        patient1.setPrimaryDoctor(textPrimaryDoctor.getText());
        patient1.setOnMedication(dropdownOnMedication.getSelectedItem().toString());
        patient1.setAllergies(dropdownAllergies.getSelectedItem().toString());
        
        
        JOptionPane.showMessageDialog(this, "Patient Information Saved");
        
    }//GEN-LAST:event_buttonSave1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSave1;
    private javax.swing.JComboBox<String> dropdownAllergies;
    private javax.swing.JComboBox<String> dropdownOnMedication;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelCreatePatient;
    private javax.swing.JLabel labelPatientID;
    private javax.swing.JLabel labelPatientName;
    private javax.swing.JLabel labelPrimaryDoctor;
    private javax.swing.JTextField textPatientID;
    private javax.swing.JTextField textPatientName;
    private javax.swing.JTextField textPrimaryDoctor;
    // End of variables declaration//GEN-END:variables
}
