/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Address;
import Model.Doctor;
import Model.Driver;
import Model.Insurance;
import Model.Patient;
import Model.Person;
import Model.VehicleRegistration;

/**
 *
 * @author rohan
 */
public class DisplayReportJPanel extends javax.swing.JPanel {

    /**
     * Creates new form displayReport
     */
    
    Address add;
    Doctor doctor;
    Driver driver;
    Insurance insurance;
    Patient patient;
    Person person;
    VehicleRegistration vehicleRegistration;
    
    public DisplayReportJPanel(Address a, Doctor doc, Driver dr, Insurance ins, Patient pat, Person p,VehicleRegistration vr) {
        initComponents();
        this.add=a;
        this.doctor=doc;
        this.driver=dr;
        this.patient=pat;
        this.person=p;
        this.vehicleRegistration=vr;
        this.insurance=ins;
        
        
        displayReport();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDisplayReport = new javax.swing.JLabel();
        dlabelPersonDetails = new javax.swing.JLabel();
        dlabelFirstname = new javax.swing.JLabel();
        dlabelLastName = new javax.swing.JLabel();
        dlabelEmail = new javax.swing.JLabel();
        dlabelAge = new javax.swing.JLabel();
        dlabelGender = new javax.swing.JLabel();
        dlabelNationality = new javax.swing.JLabel();
        dlabelReligion = new javax.swing.JLabel();
        dlabelOccupation = new javax.swing.JLabel();
        dlabelContactNumber = new javax.swing.JLabel();
        dlabelHealthInformation = new javax.swing.JLabel();
        dlabelWeight = new javax.swing.JLabel();
        dtextFirstName = new javax.swing.JTextField();
        dtextLastName = new javax.swing.JTextField();
        dtextEmail = new javax.swing.JTextField();
        dtextAge = new javax.swing.JTextField();
        dtextGender = new javax.swing.JTextField();
        dtextNationality = new javax.swing.JTextField();
        dtextReligion = new javax.swing.JTextField();
        dtextOccupation = new javax.swing.JTextField();
        dtextContactNumber = new javax.swing.JTextField();
        dtextHealthInformation = new javax.swing.JTextField();
        dtextWeight = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        dlabelCountry = new javax.swing.JLabel();
        dlabelState = new javax.swing.JLabel();
        dlabelCity = new javax.swing.JLabel();
        dlabelGPSLocation = new javax.swing.JLabel();
        dtextGPSLocation = new javax.swing.JTextField();
        dtextCity = new javax.swing.JTextField();
        dtextState = new javax.swing.JTextField();
        dtextCountry = new javax.swing.JTextField();
        dlabelDriverDetails = new javax.swing.JLabel();
        dlabelCarManufacturer = new javax.swing.JLabel();
        dtextDriverLicenseNumber = new javax.swing.JTextField();
        dlabelVehicleRegistration = new javax.swing.JLabel();
        dlabelDriverLicenseNumber1 = new javax.swing.JLabel();
        dlabelModel = new javax.swing.JLabel();
        dlabelSerialNumber = new javax.swing.JLabel();
        dlabelFuelType = new javax.swing.JLabel();
        dtextCarManufacturer = new javax.swing.JTextField();
        dtextModel = new javax.swing.JTextField();
        dtextSerialNumber = new javax.swing.JTextField();
        dtextFuelType = new javax.swing.JTextField();
        dlabelPatientDetails = new javax.swing.JLabel();
        dlabelPatientID = new javax.swing.JLabel();
        dlabelPrimaryDoctor = new javax.swing.JLabel();
        dlabelOnMedication = new javax.swing.JLabel();
        dlabelAllergies = new javax.swing.JLabel();
        dlabelPatientName = new javax.swing.JLabel();
        dtextPatientName = new javax.swing.JTextField();
        dtextPatientID = new javax.swing.JTextField();
        dtextPrimaryDoctor = new javax.swing.JTextField();
        dtextOnMedication = new javax.swing.JTextField();
        dtextAllergies = new javax.swing.JTextField();
        dlabelDoctorDetails = new javax.swing.JLabel();
        dlabelDoctorName = new javax.swing.JLabel();
        dlabelOfficeAddress = new javax.swing.JLabel();
        dlabelDoctorID = new javax.swing.JLabel();
        dlabelSpeciality = new javax.swing.JLabel();
        dlabelMedicalSchool = new javax.swing.JLabel();
        dlabelExperience = new javax.swing.JLabel();
        dlabelMedicalLicenseNumber = new javax.swing.JLabel();
        dlabelInsuranceDetails = new javax.swing.JLabel();
        dlabelCompanyName = new javax.swing.JLabel();
        dlabelCorporateAddress = new javax.swing.JLabel();
        dlabelCorporateID = new javax.swing.JLabel();
        dlabelPremium = new javax.swing.JLabel();
        dlabelDeductable = new javax.swing.JLabel();
        dlabelBenefits = new javax.swing.JLabel();
        dtextDoctorName = new javax.swing.JTextField();
        dtextOfficeAddress = new javax.swing.JTextField();
        dtextDoctorID = new javax.swing.JTextField();
        dtextSpeciality = new javax.swing.JTextField();
        dtextMedicalSchool = new javax.swing.JTextField();
        dtextExperience = new javax.swing.JTextField();
        dtextMedicalLicenseNumber = new javax.swing.JTextField();
        dtextCompanyName = new javax.swing.JTextField();
        dtextCompanyAddress = new javax.swing.JTextField();
        dtextCorporateID = new javax.swing.JTextField();
        dtextPremium = new javax.swing.JTextField();
        dtextDeductable = new javax.swing.JTextField();
        dtextBenefits = new javax.swing.JTextField();

        labelDisplayReport.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelDisplayReport.setText("Report");

        dlabelPersonDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dlabelPersonDetails.setText("Person Details");

        dlabelFirstname.setText("First Name");

        dlabelLastName.setText("Last Name");

        dlabelEmail.setText("E mail");

        dlabelAge.setText("Age");

        dlabelGender.setText("Gender");

        dlabelNationality.setText("Nationality");

        dlabelReligion.setText("Religion");

        dlabelOccupation.setText("Occupation");

        dlabelContactNumber.setText("Contact Number");

        dlabelHealthInformation.setText("Health Information");

        dlabelWeight.setText("Weight(lbs)");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Address Details");

        dlabelCountry.setText("Country");

        dlabelState.setText("State");

        dlabelCity.setText("City");

        dlabelGPSLocation.setText("GPS Location");

        dlabelDriverDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dlabelDriverDetails.setText("Driver Details");

        dlabelCarManufacturer.setText("Car Manufacturer");

        dlabelVehicleRegistration.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dlabelVehicleRegistration.setText("Vehicle Registration");

        dlabelDriverLicenseNumber1.setText("Driver License Number");

        dlabelModel.setText("Model");

        dlabelSerialNumber.setText("Serial Number");

        dlabelFuelType.setText("Fuel Type");

        dtextModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtextModelActionPerformed(evt);
            }
        });

        dtextSerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtextSerialNumberActionPerformed(evt);
            }
        });

        dtextFuelType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dtextFuelTypeActionPerformed(evt);
            }
        });

        dlabelPatientDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dlabelPatientDetails.setText("Patient Details");

        dlabelPatientID.setText("Patient ID");

        dlabelPrimaryDoctor.setText("Primary Doctor");

        dlabelOnMedication.setText("On Medication");

        dlabelAllergies.setText("Allergies");

        dlabelPatientName.setText("Patient Name");

        dlabelDoctorDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dlabelDoctorDetails.setText("DoctorDetails");

        dlabelDoctorName.setText("Doctor Name");

        dlabelOfficeAddress.setText("Office Address");

        dlabelDoctorID.setText("Doctor ID");

        dlabelSpeciality.setText("Speciality");

        dlabelMedicalSchool.setText("Medical School");

        dlabelExperience.setText("Experience");

        dlabelMedicalLicenseNumber.setText("Medical License Number");

        dlabelInsuranceDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        dlabelInsuranceDetails.setText("Insurance Details");

        dlabelCompanyName.setText("Company Name");

        dlabelCorporateAddress.setText("Company Address");

        dlabelCorporateID.setText("Corporate ID");

        dlabelPremium.setText("Premium");

        dlabelDeductable.setText("Deductable");

        dlabelBenefits.setText("Benefits");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(512, 512, 512)
                        .addComponent(labelDisplayReport))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(dlabelPersonDetails)
                                .addGap(219, 219, 219)
                                .addComponent(dlabelDriverDetails))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dlabelFirstname)
                                    .addComponent(dlabelLastName)
                                    .addComponent(dlabelEmail)
                                    .addComponent(dlabelAge)
                                    .addComponent(dlabelGender)
                                    .addComponent(dlabelNationality)
                                    .addComponent(dlabelReligion)
                                    .addComponent(dlabelOccupation)
                                    .addComponent(dlabelContactNumber)
                                    .addComponent(dlabelHealthInformation)
                                    .addComponent(dlabelWeight)
                                    .addComponent(dlabelGPSLocation)
                                    .addComponent(dlabelCity)
                                    .addComponent(dlabelState)
                                    .addComponent(dlabelCountry))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dtextState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                    .addComponent(dtextCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextGPSLocation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextWeight, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextHealthInformation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextContactNumber, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextOccupation, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextReligion, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextNationality, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextGender, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextAge, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextLastName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextFirstName, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dtextCountry))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(79, 79, 79)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dlabelModel)
                                                .addComponent(dlabelSerialNumber)
                                                .addComponent(dlabelFuelType)
                                                .addComponent(dlabelCarManufacturer))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(dtextSerialNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                                                .addComponent(dtextModel, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dtextCarManufacturer, javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(dtextFuelType))
                                            .addGap(3, 3, 3))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(243, 243, 243)
                                            .addComponent(dtextDriverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addComponent(dlabelVehicleRegistration))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dlabelPatientName)
                                            .addComponent(dlabelPatientID)
                                            .addComponent(dlabelPrimaryDoctor)
                                            .addComponent(dlabelOnMedication)
                                            .addComponent(dlabelAllergies))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dtextAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(dlabelDoctorDetails)
                                            .addComponent(dlabelPatientDetails)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dlabelBenefits)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtextBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dlabelDeductable)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtextDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dlabelPremium)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtextPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dlabelCorporateID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtextCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dlabelCorporateAddress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtextCompanyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dlabelCompanyName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtextCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dlabelDoctorName)
                                            .addComponent(dlabelOfficeAddress)
                                            .addComponent(dlabelDoctorID)
                                            .addComponent(dlabelSpeciality)
                                            .addComponent(dlabelMedicalSchool)
                                            .addComponent(dlabelExperience)
                                            .addComponent(dlabelMedicalLicenseNumber))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dtextMedicalLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextExperience, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextMedicalSchool, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextOfficeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(dtextDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dlabelInsuranceDetails)
                                .addGap(90, 90, 90)))))
                .addContainerGap(248, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(305, 305, 305)
                    .addComponent(dlabelDriverLicenseNumber1)
                    .addContainerGap(746, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelDisplayReport)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(dtextDriverLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, Short.MAX_VALUE)
                                .addComponent(dlabelVehicleRegistration)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelPersonDetails)
                                    .addComponent(dlabelDriverDetails))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelFirstname)
                                    .addComponent(dtextFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelLastName)
                                    .addComponent(dtextLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelEmail)
                                    .addComponent(dtextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelAge)
                            .addComponent(dtextAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlabelCarManufacturer)
                            .addComponent(dtextCarManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelPatientName)
                                    .addComponent(dtextPatientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelPatientID)
                                    .addComponent(dtextPatientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelPrimaryDoctor)
                                    .addComponent(dtextPrimaryDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelOnMedication)
                                    .addComponent(dtextOnMedication, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(dlabelPatientDetails))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dlabelAllergies)
                            .addComponent(dtextAllergies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelGender)
                            .addComponent(dtextGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlabelModel)
                            .addComponent(dtextModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelNationality)
                            .addComponent(dtextNationality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlabelSerialNumber)
                            .addComponent(dtextSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelReligion)
                            .addComponent(dtextReligion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlabelFuelType)
                            .addComponent(dtextFuelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelOccupation)
                            .addComponent(dtextOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelContactNumber)
                            .addComponent(dtextContactNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelHealthInformation)
                            .addComponent(dtextHealthInformation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelWeight)
                            .addComponent(dtextWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(dlabelDoctorDetails)
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelDoctorName)
                            .addComponent(dtextDoctorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelOfficeAddress)
                            .addComponent(dtextOfficeAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelDoctorID)
                            .addComponent(dtextDoctorID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelSpeciality)
                            .addComponent(dtextSpeciality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelMedicalSchool)
                            .addComponent(dtextMedicalSchool, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelExperience)
                            .addComponent(dtextExperience, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelMedicalLicenseNumber)
                            .addComponent(dtextMedicalLicenseNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(dlabelGPSLocation)
                                    .addComponent(dtextGPSLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(dlabelInsuranceDetails)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dlabelCompanyName)
                                    .addComponent(dtextCompanyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelCorporateAddress)
                            .addComponent(dtextCompanyAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlabelCity)
                            .addComponent(dtextCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelCorporateID)
                            .addComponent(dtextCorporateID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlabelState)
                            .addComponent(dtextState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelPremium)
                            .addComponent(dtextPremium, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dlabelCountry)
                            .addComponent(dtextCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelDeductable)
                            .addComponent(dtextDeductable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlabelBenefits)
                            .addComponent(dtextBenefits, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(98, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(134, 134, 134)
                    .addComponent(dlabelDriverLicenseNumber1)
                    .addContainerGap(635, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void dtextSerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtextSerialNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtextSerialNumberActionPerformed

    private void dtextFuelTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtextFuelTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtextFuelTypeActionPerformed

    private void dtextModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dtextModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dtextModelActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dlabelAge;
    private javax.swing.JLabel dlabelAllergies;
    private javax.swing.JLabel dlabelBenefits;
    private javax.swing.JLabel dlabelCarManufacturer;
    private javax.swing.JLabel dlabelCity;
    private javax.swing.JLabel dlabelCompanyName;
    private javax.swing.JLabel dlabelContactNumber;
    private javax.swing.JLabel dlabelCorporateAddress;
    private javax.swing.JLabel dlabelCorporateID;
    private javax.swing.JLabel dlabelCountry;
    private javax.swing.JLabel dlabelDeductable;
    private javax.swing.JLabel dlabelDoctorDetails;
    private javax.swing.JLabel dlabelDoctorID;
    private javax.swing.JLabel dlabelDoctorName;
    private javax.swing.JLabel dlabelDriverDetails;
    private javax.swing.JLabel dlabelDriverLicenseNumber1;
    private javax.swing.JLabel dlabelEmail;
    private javax.swing.JLabel dlabelExperience;
    private javax.swing.JLabel dlabelFirstname;
    private javax.swing.JLabel dlabelFuelType;
    private javax.swing.JLabel dlabelGPSLocation;
    private javax.swing.JLabel dlabelGender;
    private javax.swing.JLabel dlabelHealthInformation;
    private javax.swing.JLabel dlabelInsuranceDetails;
    private javax.swing.JLabel dlabelLastName;
    private javax.swing.JLabel dlabelMedicalLicenseNumber;
    private javax.swing.JLabel dlabelMedicalSchool;
    private javax.swing.JLabel dlabelModel;
    private javax.swing.JLabel dlabelNationality;
    private javax.swing.JLabel dlabelOccupation;
    private javax.swing.JLabel dlabelOfficeAddress;
    private javax.swing.JLabel dlabelOnMedication;
    private javax.swing.JLabel dlabelPatientDetails;
    private javax.swing.JLabel dlabelPatientID;
    private javax.swing.JLabel dlabelPatientName;
    private javax.swing.JLabel dlabelPersonDetails;
    private javax.swing.JLabel dlabelPremium;
    private javax.swing.JLabel dlabelPrimaryDoctor;
    private javax.swing.JLabel dlabelReligion;
    private javax.swing.JLabel dlabelSerialNumber;
    private javax.swing.JLabel dlabelSpeciality;
    private javax.swing.JLabel dlabelState;
    private javax.swing.JLabel dlabelVehicleRegistration;
    private javax.swing.JLabel dlabelWeight;
    private javax.swing.JTextField dtextAge;
    private javax.swing.JTextField dtextAllergies;
    private javax.swing.JTextField dtextBenefits;
    private javax.swing.JTextField dtextCarManufacturer;
    private javax.swing.JTextField dtextCity;
    private javax.swing.JTextField dtextCompanyAddress;
    private javax.swing.JTextField dtextCompanyName;
    private javax.swing.JTextField dtextContactNumber;
    private javax.swing.JTextField dtextCorporateID;
    private javax.swing.JTextField dtextCountry;
    private javax.swing.JTextField dtextDeductable;
    private javax.swing.JTextField dtextDoctorID;
    private javax.swing.JTextField dtextDoctorName;
    private javax.swing.JTextField dtextDriverLicenseNumber;
    private javax.swing.JTextField dtextEmail;
    private javax.swing.JTextField dtextExperience;
    private javax.swing.JTextField dtextFirstName;
    private javax.swing.JTextField dtextFuelType;
    private javax.swing.JTextField dtextGPSLocation;
    private javax.swing.JTextField dtextGender;
    private javax.swing.JTextField dtextHealthInformation;
    private javax.swing.JTextField dtextLastName;
    private javax.swing.JTextField dtextMedicalLicenseNumber;
    private javax.swing.JTextField dtextMedicalSchool;
    private javax.swing.JTextField dtextModel;
    private javax.swing.JTextField dtextNationality;
    private javax.swing.JTextField dtextOccupation;
    private javax.swing.JTextField dtextOfficeAddress;
    private javax.swing.JTextField dtextOnMedication;
    private javax.swing.JTextField dtextPatientID;
    private javax.swing.JTextField dtextPatientName;
    private javax.swing.JTextField dtextPremium;
    private javax.swing.JTextField dtextPrimaryDoctor;
    private javax.swing.JTextField dtextReligion;
    private javax.swing.JTextField dtextSerialNumber;
    private javax.swing.JTextField dtextSpeciality;
    private javax.swing.JTextField dtextState;
    private javax.swing.JTextField dtextWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelDisplayReport;
    // End of variables declaration//GEN-END:variables

    private void displayReport() {
        
        
        dtextFirstName.setText(person.getFirstName());
        dtextLastName.setText(person.getLastName());
        dtextEmail.setText(person.getEmail());
        dtextAge.setText(person.getAge());
        dtextGender.setText(person.getGender());
        dtextNationality.setText(person.getNationality());
        dtextReligion.setText(person.getReligion());
        dtextOccupation.setText(person.getReligion());
        dtextContactNumber.setText(person.getContactNumber());
        dtextHealthInformation.setText(person.getHealthInformation());
        dtextWeight.setText(person.getWeight());
        
        
        dtextGPSLocation.setText(add.getGpsLocation());
        dtextCity.setText(add.getCity());
        dtextState.setText(add.getState());
        dtextCountry.setText(add.getCountry());
        
        
        dtextDriverLicenseNumber.setText(driver.getDriverLicenseNumber());
        
        
        dtextCarManufacturer.setText(vehicleRegistration.getCarManufacturer());
        dtextModel.setText(vehicleRegistration.getModel());
        dtextSerialNumber.setText(vehicleRegistration.getSerialNumber());
        dtextFuelType.setText(vehicleRegistration.getFuelType());
        
        
        dtextPatientName.setText(patient.getPatientName());
        dtextPatientID.setText(patient.getPatientID());
        dtextPrimaryDoctor.setText(patient.getPrimaryDoctor());
        dtextOnMedication.setText(patient.getOnMedication());
        dtextAllergies.setText(patient.getAllergies());
        
        
        dtextDoctorName.setText(doctor.getDoctorName());
        dtextOfficeAddress.setText(doctor.getOfficeAddress());
        dtextDoctorID.setText(doctor.getDoctorID());
        dtextSpeciality.setText(doctor.getSpeciality());
        dtextMedicalSchool.setText(doctor.getMedicalSchool());
        dtextExperience.setText(doctor.getExperience());
        dtextMedicalLicenseNumber.setText(doctor.getMedicalLicenseNumber());
        
        
        dtextCompanyName.setText(insurance.getCompanyName());
        dtextCompanyAddress.setText(insurance.getCompanyAddress());
        dtextCorporateID.setText(insurance.getCorporateID());
        dtextPremium.setText(insurance.getPremium());
        dtextDeductable.setText(insurance.getDeductable());
        dtextBenefits.setText(insurance.getBenefits());
        
        
        System.out.println("   Person Details \n ");
        System.out.println("First Name : "+person.getFirstName());
        System.out.println("Last Name : "+person.getLastName());
        System.out.println("E-mail : "+person.getEmail());
        System.out.println("Age : "+person.getAge());
        System.out.println("Gender : "+person.getGender());
        System.out.println("Nationality : "+person.getNationality());
        System.out.println("Religion : "+person.getReligion());
        System.out.println("Occupation : "+person.getoccupation());
        System.out.println("Contact Number : "+person.getContactNumber());
        System.out.println("Health Information : "+person.getHealthInformation());
        System.out.println("Weight(lbs) : "+person.getWeight());
        
        
        
        System.out.println("\n\n  Address Details \n ");
        System.out.println("GPS Location : "+add.getGpsLocation());
        System.out.println("City : "+add.getCity());
        System.out.println("State : "+add.getState());
        System.out.println("Country : "+add.getCountry());
        
        
        
        System.out.println("\n\n  Driver Details \n ");
        System.out.println("Driver License Number : "+driver.getDriverLicenseNumber());
        
        
        
        System.out.println("\n\n  Vehicle Registration Details \n ");
        System.out.println("Car Manufacturer : "+vehicleRegistration.getCarManufacturer());
        System.out.println("Model : "+vehicleRegistration.getModel());
        System.out.println("Serial Number : "+vehicleRegistration.getSerialNumber());
        System.out.println("Fuel Type : "+vehicleRegistration.getFuelType());
        
        
        
        System.out.println("\n\n  Patient Details \n ");
        System.out.println("Patient Name : "+patient.getPatientName());
        System.out.println("Patient ID : "+patient.getPatientID());
        System.out.println("Primary Doctor : "+patient.getPrimaryDoctor());
        System.out.println("On Medication ? "+patient.getOnMedication());
        System.out.println("Allergies ? "+patient.getAllergies());        
        
        
        
        System.out.println("\n\n  Doctor Details \n ");
        System.out.println("Doctor Name : "+doctor.getDoctorName());
        System.out.println("Office Address : "+doctor.getOfficeAddress());
        System.out.println("Doctor ID : "+doctor.getDoctorID());
        System.out.println("Speciality : "+doctor.getSpeciality());
        System.out.println("Medical School : "+doctor.getMedicalSchool());
        System.out.println("Experience : "+doctor.getExperience());
        System.out.println("Medical License Number : "+doctor.getMedicalLicenseNumber());
        
        
        
        
        System.out.println("\n\n  Insurance Details \n ");
        System.out.println("Company Name : "+insurance.getCompanyName());
        System.out.println("Company Address : "+insurance.getCompanyAddress());
        System.out.println("Corporate ID : "+insurance.getCorporateID());
        System.out.println("Premium : "+insurance.getPremium());
        System.out.println("Deductables : "+insurance.getDeductable());
        System.out.println("Benefits : "+insurance.getBenefits());
        
        
        
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
