/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Model.Address;
import Model.Doctor;
import Model.Driver;
import Model.Insurance;
import Model.Patient;
import Model.Person;
import Model.VehicleRegistration;

/**
 *
 * @author rohan
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    Address add;
    Doctor doc;
    Driver driver;
    Insurance insurance;
    Patient patient;
    Person person;
    VehicleRegistration regn;
    
    
    
    
    public Home() {
        initComponents();
        person = new Person();
        add = new Address();
        doc = new Doctor();
        driver = new Driver();
        insurance = new Insurance();
        patient = new Patient();
        regn = new VehicleRegistration();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        buttonCreatePerson = new javax.swing.JButton();
        buttonCreateAddress = new javax.swing.JButton();
        buttonCreateDriver = new javax.swing.JButton();
        buttonCreateVehicleRegistration = new javax.swing.JButton();
        buttonCreatePatient = new javax.swing.JButton();
        buttonCreateDoctor = new javax.swing.JButton();
        buttonCreateInsuranceCoverage = new javax.swing.JButton();
        buttonGenerateReport = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonCreatePerson.setText("Create Person");
        buttonCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreatePersonActionPerformed(evt);
            }
        });

        buttonCreateAddress.setText("Create address");
        buttonCreateAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateAddressActionPerformed(evt);
            }
        });

        buttonCreateDriver.setText("Create Driver");
        buttonCreateDriver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateDriverActionPerformed(evt);
            }
        });

        buttonCreateVehicleRegistration.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        buttonCreateVehicleRegistration.setText("Create Vehicle Registration");
        buttonCreateVehicleRegistration.setToolTipText("");
        buttonCreateVehicleRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateVehicleRegistrationActionPerformed(evt);
            }
        });

        buttonCreatePatient.setText("Create Patient");
        buttonCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreatePatientActionPerformed(evt);
            }
        });

        buttonCreateDoctor.setText("Create Doctor");
        buttonCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateDoctorActionPerformed(evt);
            }
        });

        buttonCreateInsuranceCoverage.setText("Create Insurance Coverage");
        buttonCreateInsuranceCoverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateInsuranceCoverageActionPerformed(evt);
            }
        });

        buttonGenerateReport.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        buttonGenerateReport.setText("Generate Report");
        buttonGenerateReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGenerateReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(buttonCreatePerson, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(buttonCreateAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(buttonCreateInsuranceCoverage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCreateDoctor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCreatePatient, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCreateVehicleRegistration, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buttonCreateDriver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buttonGenerateReport)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(buttonCreatePerson)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCreateAddress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreateDriver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreateVehicleRegistration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreatePatient)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCreateDoctor)
                .addGap(18, 18, 18)
                .addComponent(buttonCreateInsuranceCoverage)
                .addGap(43, 43, 43)
                .addComponent(buttonGenerateReport)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreatePersonActionPerformed
        // TODO add your handling code here:
        CreatePersonJPanel createPersonJPanel = new CreatePersonJPanel(person);
        
        jSplitPane1.setRightComponent(createPersonJPanel);
        
        
        
        
        
        
        
    }//GEN-LAST:event_buttonCreatePersonActionPerformed

    private void buttonCreateVehicleRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateVehicleRegistrationActionPerformed
        // TODO add your handling code here:
        CreateVehicleRegistrationJPanel createVehicleRegistrationJPanel = new CreateVehicleRegistrationJPanel(regn);
        
        jSplitPane1.setRightComponent(createVehicleRegistrationJPanel);
        
    }//GEN-LAST:event_buttonCreateVehicleRegistrationActionPerformed

    private void buttonGenerateReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGenerateReportActionPerformed
        // TODO add your handling code here:
        DisplayReportJPanel displayReportJPanel=new DisplayReportJPanel(add, doc, driver, insurance, patient, person, regn);
        
        jSplitPane1.setRightComponent(displayReportJPanel);
    }//GEN-LAST:event_buttonGenerateReportActionPerformed

    private void buttonCreateAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateAddressActionPerformed
        // TODO add your handling code here:
        CreateAddressJPanel createAddressJpanel = new CreateAddressJPanel(add);
        
        jSplitPane1.setRightComponent(createAddressJpanel);
    }//GEN-LAST:event_buttonCreateAddressActionPerformed

    private void buttonCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateDoctorActionPerformed
        // TODO add your handling code here:
        CreateDoctorJPanel createDoctorJPanel = new CreateDoctorJPanel(doc);
        
        jSplitPane1.setRightComponent(createDoctorJPanel);
    }//GEN-LAST:event_buttonCreateDoctorActionPerformed

    private void buttonCreateDriverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateDriverActionPerformed
        // TODO add your handling code here:
        CreateDriverJPanel createDriverJPanel = new CreateDriverJPanel(driver);
        
        jSplitPane1.setRightComponent(createDriverJPanel);
    }//GEN-LAST:event_buttonCreateDriverActionPerformed

    private void buttonCreateInsuranceCoverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreateInsuranceCoverageActionPerformed
        // TODO add your handling code here:
        CreateInsuranceJPanel createInsuranceJPanel= new CreateInsuranceJPanel(insurance);
        
        jSplitPane1.setRightComponent(createInsuranceJPanel);
    }//GEN-LAST:event_buttonCreateInsuranceCoverageActionPerformed

    private void buttonCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCreatePatientActionPerformed
        // TODO add your handling code here:
        CreatePatientJPanel createPatientJPanel = new CreatePatientJPanel(patient);
        
        jSplitPane1.setRightComponent(createPatientJPanel);
    }//GEN-LAST:event_buttonCreatePatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCreateAddress;
    private javax.swing.JButton buttonCreateDoctor;
    private javax.swing.JButton buttonCreateDriver;
    private javax.swing.JButton buttonCreateInsuranceCoverage;
    private javax.swing.JButton buttonCreatePatient;
    private javax.swing.JButton buttonCreatePerson;
    private javax.swing.JButton buttonCreateVehicleRegistration;
    private javax.swing.JButton buttonGenerateReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
