/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import UserInterface.WorkAreas.FacultyRole.ProfessorDashboardJPanel;
import Model.CourseDetails;
import Model.CourseDetailsDirectory;
import Model.StudentDetailsDirectory;
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JSplitPane;
import javax.swing.JTextField;

/**
 *
 * @author rohan
 */
public class ProfessorLoginJPanel extends javax.swing.JPanel {
    
    private CourseDetailsDirectory coursedetailsdirectory;
    private JPanel container;
    private CourseDetails coursedetails;
    private StudentDetailsDirectory studentDetailsDirectory;
    private javax.swing.JTable tblCourseCatalog;
    

    /**
     * Creates new form StudentLoginJPanel
     */
    public ProfessorLoginJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField PasswordFieldProfessor, JTextField textProfessorLoginUsername, CourseDetails coursedetails) {
        
    }

    

    ProfessorLoginJPanel(JPanel container, JTextField textProfessorLoginUsername, JPasswordField PasswordFieldProfessor) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    ProfessorLoginJPanel(JPanel container, CourseDetailsDirectory coursedetailsdirectory, JPasswordField jPasswordField, JTextField textProfessorLoginUsername, CourseDetails coursedetails, StudentDetailsDirectory studentDetailsDirectory) {
       initComponents();
        
//        this.coursedetailsdirectory = new CourseDetailsDirectory();
        this.coursedetailsdirectory = coursedetailsdirectory;
        this.coursedetails = new CourseDetails();
        this.container=container;
        this.studentDetailsDirectory=studentDetailsDirectory;
//        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelProfessorLogin = new javax.swing.JLabel();
        labelProfessorLoginUsername = new javax.swing.JLabel();
        labelProfessorLoginPassword = new javax.swing.JLabel();
        textProfessorLoginUsername = new javax.swing.JTextField();
        buttonProfessorLoginSubmit = new javax.swing.JButton();
        PasswordFieldProfessor = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        labelProfessorLogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelProfessorLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelProfessorLogin.setText("Professor Login");
        labelProfessorLogin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        labelProfessorLoginUsername.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelProfessorLoginUsername.setText("Username:");
        labelProfessorLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        labelProfessorLoginPassword.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelProfessorLoginPassword.setText("Password:");
        labelProfessorLoginPassword.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        textProfessorLoginUsername.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        buttonProfessorLoginSubmit.setBackground(new java.awt.Color(153, 153, 153));
        buttonProfessorLoginSubmit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buttonProfessorLoginSubmit.setForeground(new java.awt.Color(255, 255, 255));
        buttonProfessorLoginSubmit.setText("Login");
        buttonProfessorLoginSubmit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        buttonProfessorLoginSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProfessorLoginSubmitActionPerformed(evt);
            }
        });

        PasswordFieldProfessor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelProfessorLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1417, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelProfessorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(187, 187, 187)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PasswordFieldProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(buttonProfessorLoginSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(424, 424, 424))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(labelProfessorLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textProfessorLoginUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProfessorLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordFieldProfessor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(buttonProfessorLoginSubmit)
                .addContainerGap(157, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonProfessorLoginSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProfessorLoginSubmitActionPerformed
        // TODO add your handling code here:
        
        String enteredUsername = textProfessorLoginUsername.getText();
        String enteredPassword = PasswordFieldProfessor.getText();
        
        if ((enteredPassword!=null && enteredPassword.equals("Professor123")) || (enteredUsername!=null && enteredUsername.equals("Professor")))
       
        {
            
            ProfessorDashboardJPanel panel = new ProfessorDashboardJPanel(container, coursedetailsdirectory, PasswordFieldProfessor, textProfessorLoginUsername, coursedetails,studentDetailsDirectory);
            container.add("ProfessorDashboardJPanel", panel);
            CardLayout layout =(CardLayout) container.getLayout();
            layout.next(container);  
            
        }
        
        else
            
        {
            JOptionPane.showMessageDialog(null, "Incorrect Username or Password Entered!", "Information", JOptionPane.INFORMATION_MESSAGE);
           
        }
    }//GEN-LAST:event_buttonProfessorLoginSubmitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordFieldProfessor;
    private javax.swing.JButton buttonProfessorLoginSubmit;
    private javax.swing.JLabel labelProfessorLogin;
    private javax.swing.JLabel labelProfessorLoginPassword;
    private javax.swing.JLabel labelProfessorLoginUsername;
    private javax.swing.JTextField textProfessorLoginUsername;
    // End of variables declaration//GEN-END:variables
       
}
